### ISSUE TITLE
Particles that are only hidden in the viewport don't render when the add-on is on

### ISSUE THREAD

**Issue by Asturias76** [RayMairlot/Timecode#2]
Hi, when your add-on is activated, if the "eye" in the stack modifier is not checked for the particle system, Blender doesn't render particles either with Cycles or Internal.

**Comment by RayMairlot** [comment]
Are you sure you have put this issue on the correct repository? 'Timecode' has no interaction with how things are rendered, but if you have a file which demonstrates this problem you can upload it here and I'll have a look.

**Comment by Asturias76** [comment]
Honestly, I also wondered why your add-on could have an influence on how things are rendered but I'm not a coder and I can just report what I see. I have opened a bug task here thinking it came from Blender : https://developer.blender.org/T51726 . I also made an other screencast to show you what I'm talking about :

http://photos13.free.fr/Blender/timecode_particles.avi

**Comment by RayMairlot** [comment]
Oddly, and to my surprise, I _was_ able to reproduce the bug. 

I still think it's a bug in Blender, but I will need to try and track down which specific part of the code in Timecode is causing the problem before doing a bug report to them.

**Comment by Asturias76** [comment]
Ok I hope you'll find what's wrong :).

**Comment by RayMairlot** [comment]
@Asturias76 The issue should now be fixed now. Let me know if you're still having the problem.

**Comment by Asturias76** [comment]
I tried with 2 files and it's ok. Thank you :).
